config/routes.rb
Amdb::Application.routes.draw do

  get '/logout' => "sessions#destroy"
  
  # 1. Use this route to display a login form
  get "sessions/new" => "sessions#new"
  
  # 2. Use this route to verify the email address
  # and create a cookie to remember who 
  # logged in.
  # Then redirect the user to the home page.
  post "sessions" => "sessions#create"
  
  # 3. Remove the User select from the voting
  # form, and record the vote based on the 
  # params hash and the session hash.
  
  resources :votes
  resources :users
  resources :roles
  resources :actors
  resources :movies
  resources :directors
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Amdb</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= flash[:notice] %>
  <nav>
    <%= link_to "Directors", directors_url %> |
    <%= link_to "Movies", movies_url %> |
    <%= link_to "Roles", roles_url %> |
    <%= link_to "Actors", actors_url %> |
    <%= link_to "Votes", votes_url %> |
    <%= link_to "Users", users_url %> |
    
    <% if session["user_id"].blank? %>
      <%= link_to "Sign In", "/sessions/new" %> 
    <% else %>
      Hello, <%= User.find(session["user_id"]).name %>
      <%= link_to "Sign Out", "/logout" %> 
    <% end %>
  </nav>

<ul>
<% session.keys.each do |k| %>
  <li><%= k %>: <%= session[k] %></li>
<% end %>
</ul>
<%= yield %>

</body>
</html>